In [1]:
import pandas as pd
import numpy as np

In [3]:
iris = pd.read_csv("iris.csv")

In [4]:
iris

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [5]:
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
iris.describe()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [7]:
iris.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

In [8]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [9]:
ip_columns = ["Sepal.Length","Sepal.Width","Petal.Length","Petal.Width"]

In [10]:
op_column  = ["Species"]

In [11]:
# Splitting data into train and test

Xtrain,Xtest,ytrain,ytest = train_test_split(iris[ip_columns],iris[op_column],test_size=0.3, random_state=0)

In [12]:
ignb = GaussianNB()
imnb = MultinomialNB()

In [13]:
# Building and predicting at the same time 

pred_gnb = ignb.fit(Xtrain,ytrain).predict(Xtest)
pred_mnb = imnb.fit(Xtrain,ytrain).predict(Xtest)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [14]:
# Confusion matrix GaussianNB model

confusion_matrix(ytest,pred_gnb) # GaussianNB model

array([[16,  0,  0],
       [ 0, 18,  0],
       [ 0,  0, 11]], dtype=int64)

In [15]:
pd.crosstab(ytest.values.flatten(),pred_gnb) 

col_0       setosa  versicolor  virginica
row_0                                    
setosa          16           0          0
versicolor       0          18          0
virginica        0           0         11

In [16]:
np.mean(pred_gnb==ytest.values.flatten()) 

1.0

In [17]:
# Confusion matrix GaussianNB model

confusion_matrix(ytest,pred_mnb) # GaussianNB model

array([[16,  0,  0],
       [ 0,  0, 18],
       [ 0,  0, 11]], dtype=int64)

In [18]:
pd.crosstab(ytest.values.flatten(),pred_mnb)

col_0       setosa  virginica
row_0                        
setosa          16          0
versicolor       0         18
virginica        0         11

In [19]:
np.mean(pred_mnb==ytest.values.flatten())

0.6

In [20]:
confusion_matrix(ytest,pred_mnb) # Multinomal model

array([[16,  0,  0],
       [ 0,  0, 18],
       [ 0,  0, 11]], dtype=int64)